In [1]:
# using python library numpy

In [2]:
# array matrices 

In [3]:
import numpy as np

In [4]:
#basic commands

In [5]:
a = np.arange(15).reshape(3, 5)

In [6]:
a  #print  a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.size

15

In [10]:
a.reshape((1,5,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

In [11]:
a #print a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
b = np.array( [20,30,40,50] )

In [13]:
a = np.ones((2,3), dtype=int)

In [14]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
b

array([20, 30, 40, 50])

In [16]:
B = np.arange(3)

In [17]:
B

array([0, 1, 2])

In [18]:
np.exp(B)  # exponential hoga maltab e ki power main

array([1.        , 2.71828183, 7.3890561 ])

In [19]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [20]:
B

array([0, 1, 2])

In [21]:
C = np.array([2., -1., 4.])

np.add(B, C) 

#add tabhi hi hoga jab shape same hoga dono ka

array([2., 0., 6.])

In [24]:
np.transpose(a)

array([[8., 9.],
       [6., 2.]])